name: atomicdataMB

channels:
    - defaults

dependencies:
    - python>=3.7
    - setuptools
    - numpy
    - astropy
    - pip:
      - sphinx
      - sphinx-automodapi
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - periodictable
      - mathMB
