name: nexoclom

channels:
  - anaconda
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults

dependencies:
  - pip
  - python=3.7
  - numpy
  - astropy
  - psycopg2
  - pandas
  - sphinx
  - pip:
    - periodictable
    - sphinx-rtd-theme
    - stsci-rtd-theme
      

